.gitignore
src/main/java/com/alkemy/ong/OngApplication.java
src/main/java/com/alkemy/ong/model/Role.java
src/main/java/com/alkemy/ong/repository/RolesRepository.java

The Role class and its repository is created to represent the data structure in the implementation.

featureOT149-16 Added Role class and repository 

---

src/main/java/com/alkemy/ong/model/Users.java
src/main/java/com/alkemy/ong/repository/UsersRepository.java

Create users model and users repository

---

src/main/resources/application.properties
src/main/resources/data.sql

- Added config in application.properties to enable data insert by SQL script.
- Added file data.sql to insert Admin and User roles in the roles table when running the application.
- JIRA ticket OT149-99

Feature/OT149-99: added script sql to insert roles in roles table

---

src/main/java/com/alkemy/ong/model/Activity.java
src/main/java/com/alkemy/ong/repository/ActivitiesRepository.java

. Activities model and repository added

feature/OT149-21 - Activity model and repository

---

src/main/java/com/alkemy/ong/controller/ControllerConstants.java
src/main/java/com/alkemy/ong/controller/v1/ActivityController.java
src/main/java/com/alkemy/ong/dto/ActivityDto.java
src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
src/main/java/com/alkemy/ong/model/Activity.java
src/main/java/com/alkemy/ong/repository/ActivitiesRepository.java
src/main/java/com/alkemy/ong/service/ActivityService.java
src/main/java/com/alkemy/ong/service/impl/ActivityServiceImp.java

.Endpoint to create activities added with all needed resources

Feature/OT149-50: Endpoint activities create

---

src/main/java/com/alkemy/ong/model/Category.java
src/main/java/com/alkemy/ong/model/Member.java
src/main/java/com/alkemy/ong/model/New.java
src/main/java/com/alkemy/ong/model/Organization.java
src/main/java/com/alkemy/ong/model/Testimonial.java
src/main/java/com/alkemy/ong/model/User.java

fix: entities

---

src/main/java/com/alkemy/ong/controller/ControllerConstants.java
src/main/java/com/alkemy/ong/controller/v1/AuthController.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

. send welcome email integrated

feature/OT149-30: welcome email

---

src/main/java/com/alkemy/ong/controller/v1/ActivityController.java
src/main/java/com/alkemy/ong/exception/ActivityNotFoundException.java
src/main/java/com/alkemy/ong/service/ActivityService.java
src/main/java/com/alkemy/ong/service/impl/ActivityServiceImp.java

. endpoint and resources needed to update activities added

feature/OT149-51: endpoint update activities

---

src/main/java/com/alkemy/ong/dto/ContactDto.java
src/main/java/com/alkemy/ong/mapper/ContactMapper.java
src/main/java/com/alkemy/ong/model/Contact.java
src/main/java/com/alkemy/ong/repository/ContactsRepository.java
src/main/java/com/alkemy/ong/service/ContactService.java
src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java

-Added model, service and repository of contact.
-Added ContactDto and ContactMapper
-Jira Ticket OT149-53

[OT149-53] Added model, service and repository of contact

---

src/main/java/com/alkemy/ong/controller/v1/AuthController.java
src/main/java/com/alkemy/ong/repository/UserRepository.java
src/main/java/com/alkemy/ong/service/AuthService.java
src/main/java/com/alkemy/ong/service/impl/AuthServiceImpl.java

Added getUserLogged method and implementation
Added  getUserLogget Get Request in AuthController
- JIRA Ticket OT149-36:
COMO usuario
QUIERO obtener mis datos
PARA tener conocimiento de la información que almaceno en el sistema
/GET auth/me - Deberá devolver los datos del usuario autenticado, obteniendo al mismo desde el token enviado en el header Authorization

[OT149-36] Added getUserLogget Get Request in AuthControlle

---

src/main/java/com/alkemy/ong/controller/ControllerConstants.java
src/main/java/com/alkemy/ong/controller/v1/MemberController.java
src/main/java/com/alkemy/ong/dto/MemberDto.java
src/main/java/com/alkemy/ong/mapper/MemberMapper.java
src/main/java/com/alkemy/ong/model/Member.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java

.Endpoint and resources to get all members added

[OT149-68] Endpoint get members

---

src/main/java/com/alkemy/ong/enumeration/ApplicationErrorCode.java
src/main/java/com/alkemy/ong/enumeration/Location.java
src/main/java/com/alkemy/ong/exception/AbstractExceptionHandler.java
src/main/java/com/alkemy/ong/exception/ErrorDetails.java
src/main/java/com/alkemy/ong/exception/GlobalControllerExceptionHandler.java

- Added ErrorDetails class
- Added AbstractExceptionHandler class
- Added Location enumeration
- Added ApplicationErrorCode enumeration
- Now GlobalControllerExceptionHandler extends of AbstractExceptionHandler
https://alkemy-labs.atlassian.net/browse/OT149-101?atlOrigin=eyJpIjoiMWUxYjI3MGZiNjEzNGNmZTkwN2MzNDA0MzhjNWU0MGUiLCJwIjoiaiJ9
- Con el fin de unificar criterios con respecto a el manejos de errores se pide: 
- Crear una clase ErrorDetails y los enums correspondientes:
- Modificar la clase GlobalControllerExceptionHandler para que extienda de la clase siguiente:

[OT149-101] Refactorizar - Error DTO

---

src/main/java/com/alkemy/ong/controller/ControllerConstants.java
src/main/java/com/alkemy/ong/controller/v1/ContactController.java
src/main/java/com/alkemy/ong/dto/ApiErrorDto.java
src/main/java/com/alkemy/ong/dto/ContactDto.java
src/main/java/com/alkemy/ong/exception/GlobalControllerExceptionHandler.java
src/main/java/com/alkemy/ong/mapper/ContactMapper.java
src/main/java/com/alkemy/ong/model/Contact.java
src/main/java/com/alkemy/ong/service/ContactService.java
src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java

- Added POST endpoint to save new contacts
- Added ApiErrorDto class with input data validation
- Added @ Override handleMethodArgumentNotValid in GlobalControllerExceptionHandler
- Jira Ticket OT149-54
COMO usuario
QUIERO dar de alta contactos
PARA que estén en la base de datos
- Se debe hacer una petición POST /contacts 
- Se verificará que la petición contenga los campos name y email

[OT149-54] Added POST endpoint to save new contacts

---

src/main/java/com/alkemy/ong/controller/v1/MemberController.java
src/main/java/com/alkemy/ong/dto/MemberDto.java
src/main/java/com/alkemy/ong/model/Member.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java

. Endpoint to create members added

[OT149-69] Endpoint create members

---

src/main/java/com/alkemy/ong/controller/v1/MemberController.java
src/main/java/com/alkemy/ong/service/MemberService.java
src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java

. Endpoint to delete members and resources added

[OT149-70] Endpoint delete members

---

pom.xml
src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
src/main/java/com/alkemy/ong/controller/v1/ActivityController.java
src/main/java/com/alkemy/ong/controller/v1/AuthController.java
src/main/java/com/alkemy/ong/controller/v1/CategoryController.java
src/main/java/com/alkemy/ong/controller/v1/ContactController.java
src/main/java/com/alkemy/ong/controller/v1/ImageUploadController.java
src/main/java/com/alkemy/ong/controller/v1/MemberController.java
src/main/java/com/alkemy/ong/controller/v1/NewController.java
src/main/java/com/alkemy/ong/controller/v1/OrganizationController.java
src/main/java/com/alkemy/ong/controller/v1/TestimonialController.java
src/main/java/com/alkemy/ong/controller/v1/UserController.java
src/main/resources/application.properties

* Add Swagger to the controllers
* Add  Swagger endpoints to Spring Security
*  Add Swagger dependency to pom.xml

[OT149-84] Add Swagger to the project

---

src/main/java/com/alkemy/ong/dto/SlideDto.java
src/main/java/com/alkemy/ong/mapper/SlideMapper.java
src/main/java/com/alkemy/ong/model/Slide.java
src/main/java/com/alkemy/ong/repository/SlideRepository.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java

feature/OT149: Crear Modelo y Repositorio de Slides

---

src/main/java/com/alkemy/ong/model/Comment.java
src/main/java/com/alkemy/ong/repository/CommentRepository.java
src/main/java/com/alkemy/ong/service/CommentService.java

- JIRA Ticket OT149-74:
COMO usuario 
QUIERO agregar un nuevo comentario a una novedad
PARA opinar acerca de dicha novedad
Se agregará la posibilidad de agregar Comentarios a una Novedad. Los campos de un comentario serán user_id, body y news_id

[OT149-74] Added model, repository and Service for Comments

---

src/main/java/com/alkemy/ong/controller/v1/NewController.java
src/main/java/com/alkemy/ong/exception/GlobalControllerExceptionHandler.java
src/main/java/com/alkemy/ong/service/NewService.java
src/main/java/com/alkemy/ong/service/impl/NewServiceImpl.java

* Create delete news method
* Create Exception Handler

[OT149-48] Add delete news method

---

src/main/java/com/alkemy/ong/controller/ControllerConstants.java
src/main/java/com/alkemy/ong/controller/v1/SlideController.java
src/main/java/com/alkemy/ong/dto/SlideDetailDto.java
src/main/java/com/alkemy/ong/mapper/SlideMapper.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java

OT149-55: Endpoint Listado de Slides

---

src/main/java/com/alkemy/ong/dto/OrganizationPutDto.java
src/main/java/com/alkemy/ong/model/Organization.java
src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java

*Add contact fields (Instagram, Facebook, Linkedin) to model, OrganizationServiceImpl and OrganizationPutDto

[OT149-63]Add contact fields to organizations

---

src/main/java/com/alkemy/ong/dto/OrganizationPutDto.java
src/main/java/com/alkemy/ong/dto/OrganizationResponseDto.java
src/main/java/com/alkemy/ong/model/Organization.java
src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java

* Add contact fields to OrganizationResponseDto

[OT149-64] Add contact fields to Organization response

---

src/main/java/com/alkemy/ong/controller/v1/CommentController.java
src/main/java/com/alkemy/ong/mapper/CommentMapper.java
src/main/java/com/alkemy/ong/repository/CommentRepository.java
src/main/java/com/alkemy/ong/service/CommentService.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java

- JIRA Ticket 79
- Criterios de aceptación:
- GET /posts/:id/comments - Devolverá todos los Comentarios pertenecientes a un post

[OT149-79] Endpoint para listar Comentarios en base a un post

---

src/main/java/com/alkemy/ong/configuration/SwaggerConfig.java
src/main/java/com/alkemy/ong/controller/v1/AuthController.java

- Added documentation to POST /login endpoint on AuthController
- Added configuration to SwagerConfig class for use the "Authorize" button with token in Swagger
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de autenticación
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

[OT149-89] Added documentation to POST /login endpoint

---

src/main/java/com/alkemy/ong/configuration/SwaggerConfig.java
src/main/java/com/alkemy/ong/controller/v1/CommentController.java
src/main/java/com/alkemy/ong/controller/v1/TestimonialController.java

- Added documentation to endpoints in TestimonialController
COMO desarrollador
QUIERO disponer de una documentación de los endpoints de Testimonios
PARA tener referencias de su funcionamiento
Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

[OT149-88] Added documentation in the Testimonials Controller

---

src/main/java/com/alkemy/ong/controller/v1/SlideController.java
src/main/java/com/alkemy/ong/service/SlideService.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java

Feat OT149-59: Endpoint Delete Slides

---

src/main/java/com/alkemy/ong/controller/v1/UserController.java
src/main/java/com/alkemy/ong/dto/UserPagedList.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

GET a /users . Devolverá un listado de todos los Usuarios. Este endpoint solo deberá ser accesible por los Usuarios administradores.

[OT149-87] Endpoint get all users

---

src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java

- Motivation and Summary
- JIRA Ticket OT149-104:
Post v1/comments validar existencia de user y de new

[OT149-104] Update CommentServiceImpl.java

---

src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java

- JIRA Ticket OT149-103
No está validando la existencia y actualizando cuando existe, al llamar a:

[OT149-103] Testimonial PUT error

---

src/main/java/com/alkemy/ong/controller/v1/CategoryController.java

* Add documentation to category controller

[OT149-85] Add swagger to category controller

---

src/main/java/com/alkemy/ong/dto/CategoryDto.java

[OT149-110] Fix regex en atributo name de CategoryDto

---

src/main/java/com/alkemy/ong/configuration/SecurityConfig.java

* Protect admin routes (POST, PUT, DELETE) with JWT

[OT149-73] Protect admin routes with JWT

---

src/main/java/com/alkemy/ong/controller/v1/MemberController.java

Se deberán documentar los diferentes endpoints especificando el modelo de datos, campos obligatorios, formato de la petición y ejemplo de la misma.

[OT149-87] Member documentation added

---

src/main/java/com/alkemy/ong/controller/v1/NewController.java

[OT149-111] Agregar el Path Completo en POST de New Controller

---

src/main/java/com/alkemy/ong/service/impl/ActivityServiceImp.java
src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/NewServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

Agregar @Transactional a los métodos en los Service que hagan operaciones CUD (POST, PUT, PATCH, DELETE) y @Transactional(readOnly = true) a los métodos de consulta (GET).

[OT149-107] Transactional annotation in services added

---

src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java

- Motivation and Summary
- JIRA Ticket OT149-114

[OT149-114] Bug fix: method in PUT Comment endpoint not working

---

src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
src/main/java/com/alkemy/ong/controller/v1/NewController.java
src/main/java/com/alkemy/ong/controller/v1/OrganizationController.java

[OT149-113] Bug fix: Endpoint para de datos públicos de Organización

---

src/main/java/com/alkemy/ong/dto/NewDetailDto.java
src/main/java/com/alkemy/ong/dto/NewDto.java
src/test/java/com/alkemy/ong/controller/v1/NewControllerIT.java
src/test/java/com/alkemy/ong/controller/v1/NewControllerTest.java

- JIRA Ticket 93
- Criterios de aceptación:
Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.

[OT149-93] Test: Endpoints /news

---

src/main/java/com/alkemy/ong/dto/ContactDto.java
src/test/java/com/alkemy/ong/controller/v1/ContactControllerIT.java
src/test/java/com/alkemy/ong/controller/v1/ContactControllerTest.java

[OT149-95] Test: Contact endpoints

---

src/main/java/com/alkemy/ong/configuration/SecurityConfig.java

[OT149-116] Fix: configure method on SecurityConfig

---

src/main/java/com/alkemy/ong/controller/v1/ActivityController.java
src/main/java/com/alkemy/ong/dto/ActivityDto.java
src/test/java/com/alkemy/ong/controller/v1/ActivityControllerIT.java
src/test/java/com/alkemy/ong/controller/v1/ActivityControllerTest.java

* Add integration test and unit test to activities endpoint
*  Fix response URI of activities controller endpoint

[OT149-94] Test activities endpoint

---

src/main/java/com/alkemy/ong/service/impl/AuthServiceImpl.java

- JIRA Ticket OT149-118:
Cast error on User.

[OT149-118] FIX: Cast error on User.

---

src/main/java/com/alkemy/ong/mapper/UserMapper.java
src/main/java/com/alkemy/ong/service/impl/AuthServiceImpl.java

[OT149-118] fix: Removed the password field from ResponseBody

---

src/main/java/com/alkemy/ong/configuration/SecurityConfig.java
src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java

- saveUser now save the user role (predefined user role)
- fix unnecessary line in SecurityConfig ( ".authorizeRequests().antMatchers(" )
- JIRA Ticket 115

[OT149-115]fix: AuthController, SecurityConfig

---

src/main/java/com/alkemy/ong/controller/v1/ImageUploadController.java

* Add url to amazon Header Location

[OT149-112] Add url to amazon Header Location

---

src/main/java/com/alkemy/ong/controller/v1/CategoryController.java
src/main/java/com/alkemy/ong/controller/v1/MemberController.java
src/main/java/com/alkemy/ong/controller/v1/TestimonialController.java

Como buena práctica no usar las implementaciones de las interfaces de los Service al hacer DI, usar las interfaces.

[OT149-117] Bug-fixed: service interface

---

src/test/java/com/alkemy/ong/controller/v1/UserControllerIT.java
src/test/java/com/alkemy/ong/controller/v1/UserControllerTest.java

Testear el escenario de respuesta correcta, y escenarios de error, como ids inexistentes, validaciones, permisos, etc. El archivo deberá crearse dentro de la carpeta /test, con el mismo nombre del endpoint. Se puede utilizar como base el test creado a modo de demostración.

[OT149-90] Test: users tests added

---

src/main/java/com/alkemy/ong/controller/v1/UserController.java

[OT149-120] Users get documentation added
